#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    size = len(arr)
    
    num_pos = 0
    num_neg = 0
    num_zero = 0
    
    for i in arr:
        if i > 0:
            num_pos+=1
        elif i < 0:
            num_neg+=1
        elif i==0:
            num_zero+=1
    
    print(num_pos/size)
    print(num_neg/size)
    print(num_zero/size)
    
    
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
