#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'lonelyinteger' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.

# Bir dizide diğerlerinden farklı olan tek bir elemanı bulmak için XOR (özel veya) işlemi kullanabilirsiniz. XOR, karşılaştırılan iki sayının her bir biti farklı olduğunda 1, aynı olduğunda ise 0 döndüren bir bit işlemidir.
# Bu örnekte, XOR işlemi, dizideki tüm elemanları birleştirmek için kullanılır. XOR'ün özelliği, bir sayıyı kendisi ile XOR işlemine soktuğunuzda sonucun 0 olmasıdır. Bu nedenle, iki kez görünen tüm elemanlar birbirini iptal eder, yalnızca benzersiz olan eleman XOR sonucunda kalır.


def lonelyinteger(a):
    # Write your code here
    unique_element = 0
    
    for num in a:
        unique_element ^= num

    return unique_element

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = lonelyinteger(a)

    fptr.write(str(result) + '\n')

    fptr.close()
